version: "3.3"

x-restart: &restart
  restart: always

services:
  redis:
    restart: always
    image: "redis:alpine"
    hostname: redis
    <<: *restart
    command: redis-server --requirepass ${REDIS_PASS}
    expose:
      - "6379"
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16-alpine
    <<: *restart
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PW}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "0.0.0.0:5432:5432"
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}
      interval: 10s
      timeout: 2s
      retries: 10

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    <<: *restart
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PW}

volumes:
  redis-data:
  db-data:
