= Meeting-Protokoll 08.12.2025

*Datum:* 08.12.2025 +
*Ort:* Online (MS Teams) +
*Leitung:* Paula +
*Protokoll:* ... +
*Meetingbeginn:* 14:00 +
*Meetingende:* xx:xx +
*Dauer:* xx min +

==== Anwesenheit: 
- Elias
- Paula
- Khang
- Christoph
- Cedrick
- Ben

== Tagesordnung

==  Weekly Stand-up/Backlog Refinement
=== 1. Ticketfortschritt
Wie weit seit ihr? Gibts was zu besprechen? Müssen noch Aufgaben verteilt werden?

*Notizen:* +
- ... +

*Entscheidungen:* +
- ... +
  +
  +



=== 2. Wie weit sind die Tests?

*Notizen:* +
- ... +

*Entscheidungen:* +
- ... +
  +
  +



=== 3. Fachaustausch Tests

*Notizen:* +
- ... +

*Entscheidungen:* +
- ... +
  +
  +


=== 4. Infos aus der Konsultation letzte Woche
=====================
- Wer hat am 16.12. (Dienstag) um 18Uhr Zeit? → 2 Leute noch dazu
    - Meeting mit Externen zwar nach unserem Sprint Planning → einfach kurzes Update mit Begründung am Dienstag
=====================
=====================
- Termin Task-Erstellung & Sequenzdiagramme für den letzten großen Sprint (alles was wir nicht im Sprint Planning schaffen) → Elias
=====================
=====================
- Thema Test: 10% Systemtest (Lasttest = 1000 User auf einmal) oder UX-Heuristik, 20% Integrationstests und 70% Unit-Test (komplexe Stellen und Kompontenten mit hohem Wert)
=====================
=====================
- SCRUM-Master kannst du nochmal unsere Regeln (DoD und DoR) durchgehen und schauen, wie wir diese umsetzen + potenzielle Verbesserungsmaßnahmen an den Regeln oder unserer Vorgehensweise → bevor nicht getestet wurde (automatisch) kein Merge
=====================
=====================
- Feedback Sequenz - und Klassendiagramme
    - Sequenzdiagramme sind gut → nächstes Mal leicht vereinfachen und Überprüfung, der Devs, ob wir diese so umgesetzt haben, wenn nicht kurze Begründung an das Ticket, warum nicht
    - Klassendiagramm
        - DTO ist die falsche Stelle zur Validierung → Clean Architektur anschauen
        - Fachliche und technische Sicht auseinander halten → Auch in den Bewertungskriterien, daher technische User-Story für bessere Wartbarkeit und Schnelligkeit für Nutzer
=====================
=====================
- Abgabedokument durchgehen
    - Folie 1 von der Belegarbeitsabgabe
    - Alle neuen Dokumentationstasks für die nächste Iteration zeigen und zuweisen → Bitte seine Aufgabe durchlesen bis nächste Woche, damit wir es besser einplanen können
=====================

*Notizen:* +
- ... +


*Entscheidungen:* +
- ... +
  +
  +


=== 5. Bugs der letzten Woche?

*Notizen:* +
- ... +


*Entscheidungen:* +
- ... +
  +
  +



=== 6. Review durch externe Gruppe
Termin: Di 16.12 18 Uhr ? (bleibt der Termin?) +
Wer kommt mit?


*Notizen:* +
- ... +

*Entscheidungen:* +
- ... +
  +
  +



== Retrospektive
*Dinge aus dem letzten Sprint*: +
- keine Meetings mehr in Person, alles Online +
- ursprünglich Review & Retro im Meeting eine Woche vor Sprintplanung +
    -> Änderung: Retro eine Woche vor Sprintplanung im wöchentlichen Meeting, externes Review möglichst kurz vor (wenige Tage) der Sprintplanung, internes Review im gleichen Meeting wie Sprintplanung (am Anfang des Meetings) +
- ... +




=== 5. Weitere organisatorische Aufgaben und/oder offene Punkte

- ... +


== Nächstes Meeting

- Datum: 15.12.2025
- Zeit: 13:30
- Ort: Online (Teams)

==== Themen nächstes Meeting

- To-Do's aus dem Externen Review +
- Internes Review +
- Sprintplanung +