= Design: {project-name}
Ben Eisold (s87191<at>htw-dresden.de); Paula Grahlow (s86261<at>htw-dresden.de); Tuan Khang Pham (s87088<at>htw-dresden.de); Christoph Prasser (s87530<at>htw-dresden.de); Cedrick Richter (s87073<at>htw-dresden.de); Elias Blume (s87142<at>htw-dresdsen.de) 
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter f체r weitere Dokumenten-Attribute


== Zweck
Dieses Dokument beschreibt wesentliche Entwurfsentscheidungen auf Ebene der Komponenten und Module. Diese dienen als Vorgabe f체r die Implementierung und erleichtern das Systemverst채ndnis.
 
== Ausgew채hlte Sichten
//Entwurfsklassendiagramme, Sequenzdiagramme

.Beispiel, Sequenzdiagramm
[plantuml, "{diagramsdir}/example_seq", svg]
....
include::{plantumlsdir}/example_seq.puml[]
....

// .Beispiel, Klassendiagramm (C4-Level-4)
// [plantuml, "{diagramsdir}/example_class", svg]
// ....
// include::{plantumlsdir}/example_class.puml[]
//....
Siehe Datei new_classdiagram.png

== Schnittstellen
//Dokumentation oder Verweise auf Schnittstellen, z.B. REST-APIs

== Datenmodell
