= Meeting-Protokoll 12.05.2025

*Datum:* 12.05.2025 +
*Ort:* Online (MS Teams) +
*Leitung:* Paula +
*Protokoll:* Christoph +
*Meetingbeginn:* 16:00 +
*Meetingende:* 16:20 +
*Dauer:* 20 min 

==== Anwesenheit: 
- Elias
- Ben
- Paula
- Ali
- Khang
- Christoph
- Cedrick


== Tagesordnung

==  Weekly Stand-up/Backlog Refinement
=== 1. Überarbeitung Stakeholder
Stakeholder sind überarbeitet. Wer reviewt das?

*Notizen:* +
- Gemeinsam im Team reviewt +
 +
 

=== 2. Personas und User Stories ausarbeiten
Wie ist der Stand?

*Notizen:* +
- Ben hat heute angefangen und ist noch im Progress +
- Auf ca. 2-4 Personas festlegen und davon User Stories ableiten, damit es nicht zu viel und wiederholend wird +
- Personas sollen tatsächliche Nutzer darstellen (um gut User Stories ableiten zu können), also primär Studenten +
 +

=== 4. Review Meeting mit Externen

*Notizen/Diskussion*: +
- Wir laden unsere Externen einfach ins reguläre Montags-Meeting ein und stellen ihnen kurz unsere Idee und unseren aktuellen Fortschritt vor +
- Das Meeting sollte online stattfinden, da das einfach praktischer für die Externen ist +
- Voraussichtlicher Termin: 26.05. (auch wenns nicht der letzte Termin der Iteration ist) +
 +


=== 5. Weitere organisatorische Aufgaben und/oder offene Punkte

*Notizen:* +
- Aktuelle Woche werden die User Stories ausgearbeitet +
- In der Woche danach wird dann das Dev Team aktiv


== Nächstes Meeting
- Datum: 19.05.2025
- Zeit: *16:00* Uhr
- Ort: Online

=== Themen
- User Story Fortschritt, Erste Schritte Dev Team, Umzug des Repo in die Organisation geklappt?
          
