= Meeting-Protokoll 30.06.2025

*Datum:* 30.06.2025 +
*Ort:* Online (MS Teams) +
*Leitung:* Paula +
*Protokoll:* ... +
*Meetingbeginn:* 16:00 +
*Meetingende:* xx:xx +
*Dauer:* xx min 

==== Anwesenheit: 
- Elias
- Ben
- Paula
- Ali
- Khang
- Christoph
- Cedrick

== Tagesordnung

Generalprobe
Abgabedokument


==  Weekly Stand-up/Backlog Refinement
=== 1. Generalprobe
Vorführung der Präsentation. Verbesserungsvorschläge +

*Notizen:* +
- ... +


*Entscheidung:* +
- ... +

 +
 +

=== 2. Abgabedokument
- requirements/glossary.adoc +
    -> Abkürzungen und Akronyme hat noch einige auskommentierte Begriffe. Brauchen wir die oder können die weg?
- requirments/user-stories-textfom.adoc +
    -> brauchen wir die wenn sie im GitHub stehen?
- arcitecture/architecture_notebook.adoc +
    -> sind alle Daten noch aktuell/ steht dort das wofür wir uns letzten Endes entschieden haben?
- project_management/project_plan.adoc +
    -> 3.2 Entwicklungspraktiken sind noch nicht formuliert
    
 +
 +

*Notizen:* +
- ... +


*Entscheidung:* +
- ... +
 +
 +


=== 3. Fortschritt der Devs
Wie ist der Stand? Wollt ihr den Fortschritt besprechen? +

*Notizen:* +
- ... +

*Entscheidung:* +
- ... +
 +
 +
 
=== 4. Github Project-Tabs anpassen
Product Backlog = geordnete Liste von allen Sachen die im Produkt enthalten sein sollen, dient als Anforderungsquelle für alle Änderungen am Produkt +
Entstehung des Sprint Backlogs aus PBI und Tasks als Plan +

Mapping:
Overview = Product Backlog

Current Iteration - All = Sprint Backlog - All

Current Iteration - Tasks = Sprint Backlog - Tasks

Current Iteration - Docu = Sprint Backlog - Docu

User Stories = PB - User Stories

Risks = bleibt

My items = bleibt

Tasks = delete

Roadmap = bleibt

Team capacity = bleibt

Die Frage bleibt: Macht es Sinn die Doku überhaupt zum SB mit dazu zu zählen, da es keine konkreten Produkt-Aufgaben sind, sondern teilweise Aufgaben die für die Bewertung von SE1 benötigt werden oder welche die einfach nur portokolliert sind und den Prozess unterstützen

*Notizen:* +
- ... +

*Entscheidung:* +
- ... +
 +
 +

=== 5. Weitere organisatorische Aufgaben und/oder offene Punkte

*Notizen:* +
- Änderung des Wireframes dokumentieren → @Christoph kannst du bitte kurz aufschreiben, was wir geändert haben im Gegensatz zum Original, also zwei Zwischenüberschriften und dann ganz unten die Änderugen hinschreiben → docs/requirements/ux-concept.adoc +
- Konsulationsfragen zeigen und besprechen


== Nächstes Meeting

- Datum: xx.xx.2025
- Zeit: *xx:xx* Uhr
- Ort: Online (Teams)

==== Themen nächstes Meeting

- ... +
